### PR TITLE
add permissions documentation

### LINKED ISSUE #145: Add permissions note for assets
with screenshots?

### PR DESCRIPTION
**Pull request by AurelienGasser**
Close #145

### CODE REVIEW

**Comment by AurelienGasser** [comment]
@natct10  The build works now that I'm not a fork anymore :shrug: 

Can you please review this PR?

**Comment by natct10** [comment]
> @natct10 The build works now that I'm not a fork anymore shrug
> 
> Can you please review this PR?

Okay that was it then. You are now admin on the repo, all should be fine!

**Review by natct10 — APPROVED** [review]
Neat!

**Review by Esadruhn — APPROVED** [review]

**Review by RomainGoussault — APPROVED** [review]
👍

**Pull request merged**
